"use client";
import { FormEvent, useEffect, useState } from "react";
import { StagePresentation } from "@/features/stage/stage-presentation";
import { useStageSnapshot } from "@/features/stage/use-stage-snapshot";
type Block = { id: string; title: string; durationSeconds: number; position: number };
type EventItem = { id: string; title: string; status: string; plannedSeconds: number; blocks?: Block[] };
const minutes = (seconds: number) => `${Math.floor(seconds / 60)} min`;
export function ManagementClient() { const [events, setEvents] = useState<EventItem[]>([]); const [active, setActive] = useState<EventItem | null>(null); const [title, setTitle] = useState(""); const [blockTitle, setBlockTitle] = useState(""); const [blockMinutes, setBlockMinutes] = useState("30"); const { snapshot, connection, setSnapshot } = useStageSnapshot(active?.id ?? null);
  const loadEvents = async () => { const items = await (await fetch("/api/events", { cache: "no-store" })).json() as EventItem[]; setEvents(items); };
  const openEvent = async (id: string) => { const event = await (await fetch(`/api/events/${id}`)).json() as EventItem; setActive(event); };
  useEffect(() => { let cancelled = false; void fetch("/api/events", { cache: "no-store" }).then((response) => response.json()).then((items: EventItem[]) => { if (!cancelled) setEvents(items); }); return () => { cancelled = true; }; }, []);
  const createEvent = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; const created = await (await fetch("/api/events", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title }) })).json() as EventItem; setTitle(""); await loadEvents(); setActive(created); };
  const addBlock = async (event: FormEvent) => { event.preventDefault(); if (!active) return; await fetch(`/api/events/${active.id}/blocks`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: blockTitle, durationSeconds: Number(blockMinutes) * 60 }) }); setBlockTitle(""); await openEvent(active.id); await loadEvents(); };
  const command = async (type: "start" | "pause" | "resume" | "clear", blockId?: string) => { if (!active || !snapshot) return; const response = await fetch(`/api/events/${active.id}/stage/commands`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ commandId: crypto.randomUUID(), expectedVersion: snapshot.version, type, ...(blockId ? { blockId } : {}) }) }); if (response.ok) setSnapshot(await response.json()); };
  const currentBlock = active?.blocks?.find((block) => block.id === snapshot?.activeBlockId);
  return <main className="management-shell"><header><p className="eyebrow">GESTAO DE PALCO</p><h1>Console do culto</h1><span className="connection">palco: {connection}</span></header><section className="management-grid"><aside className="event-panel"><h2>Eventos</h2><form onSubmit={createEvent}><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: Culto 01 - Domingo" /><button>Criar evento</button></form><div className="event-list">{events.map((item) => <button className={active?.id === item.id ? "selected" : ""} key={item.id} onClick={() => void openEvent(item.id)}><b>{item.title}</b><small>{item.status} · {minutes(item.plannedSeconds)}</small></button>)}</div></aside><section className="console-panel">{active ? <><div className="event-heading"><div><p className="eyebrow">EVENTO ABERTO</p><h2>{active.title}</h2></div><strong>Total: {minutes(active.plannedSeconds)}</strong></div><form className="block-form" onSubmit={addBlock}><input value={blockTitle} onChange={(event) => setBlockTitle(event.target.value)} placeholder="Nome do bloco" /><input min="1" type="number" value={blockMinutes} onChange={(event) => setBlockMinutes(event.target.value)} /><button>Adicionar bloco</button></form><div className="blocks">{active.blocks?.map((block) => <article key={block.id}><div><b>{block.title}</b><small>{minutes(block.durationSeconds)}</small></div><button onClick={() => void command("start", block.id)}>Iniciar</button></article>)}</div><div className="live-controls"><button onClick={() => void command("pause")}>Pausar</button><button onClick={() => void command("resume")}>Retomar</button><button onClick={() => void command("clear")}>Limpar palco</button></div></> : <p>Crie ou selecione um evento para iniciar a preparacao.</p>}</section><section className="preview-panel"><p className="eyebrow">PREVIEW AO VIVO</p><StagePresentation snapshot={snapshot} block={currentBlock} /><small>Versao {snapshot?.version ?? "-"} · {connection}</small></section></section></main>; }
